# Generated by Django 5.0.1 on 2024-02-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
