# Generated by Django 5.0.1 on 2024-02-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0006_remove_product_page_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
