# Generated by Django 5.0.1 on 2024-02-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0012_gadgetuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GadgetUser',
        ),
    ]
