# Generated by Django 5.0.1 on 2024-02-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0014_cart_cartitem_cart_products_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
