# Generated by Django 5.0.1 on 2024-02-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0015_rename_state_order_country_remove_cart_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='New', max_length=100),
        ),
    ]
