# Generated by Django 5.0.1 on 2024-02-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0019_cartitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.TextField(default=''),
        ),
    ]
