# Generated by Django 5.0.1 on 2024-02-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0019_cartitem_total_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='gadgets_order',
        ),
    ]
