# Generated by Django 5.0.1 on 2024-02-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0021_alter_cartitem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='id',
            new_name='cartitem_id',
        ),
    ]
