# Generated by Django 5.0.1 on 2024-02-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0021_remove_order_products_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cart_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gadgets.cartitem'),
        ),
    ]
