# Generated by Django 5.0.1 on 2024-02-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0022_remove_orderitem_product_alter_orderitem_cart_item'),
        ('gadgets', '0022_rename_id_cartitem_cartitem_id'),
    ]

    operations = [
    ]
