# Generated by Django 5.0.1 on 2024-02-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0025_remove_orderitem_cart_item_order_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.TextField(blank=True),
        ),
    ]
